name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile --windowed --add-data "assets;assets" --name "IDARA DZ" main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: IDARA-DZ-Windows
          path: dist/IDARA DZ.exe
